/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bottom1: typeof import('./src/components/view/Bottom1.vue')['default']
    Bottom2: typeof import('./src/components/view/Bottom2.vue')['default']
    DeviceData: typeof import('./src/components/device/DeviceData.vue')['default']
    DeviceData1: typeof import('./src/components/device/DeviceData1.vue')['default']
    DeviceData2: typeof import('./src/components/device/DeviceData2.vue')['default']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Header2: typeof import('./src/components/content/Header2.vue')['default']
    Left1: typeof import('./src/components/view/Left1.vue')['default']
    Left2: typeof import('./src/components/view/Left2.vue')['default']
    Left4: typeof import('./src/components/view/Left4.vue')['default']
    Map: typeof import('./src/components/view/Map.vue')['default']
    Panel: typeof import('./src/components/content/Panel.vue')['default']
    Right1: typeof import('./src/components/view/Right1.vue')['default']
    Right2: typeof import('./src/components/view/Right2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubList: typeof import('./src/components/device/SubList.vue')['default']
  }
}
