/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bottom1: typeof import('./src/components/view/Bottom1.vue')['default']
    Bottom2: typeof import('./src/components/view/Bottom2.vue')['default']
    DeviceData: typeof import('./src/components/device/DeviceData.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Header: typeof import('./src/components/content/Header.vue')['default']
    Header2: typeof import('./src/components/content/Header2.vue')['default']
    HeaderTo2: typeof import('./src/components/content/HeaderTo2.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Left1: typeof import('./src/components/view/Left1.vue')['default']
    Left2: typeof import('./src/components/view/Left2.vue')['default']
    Left3: typeof import('./src/components/view/Left3.vue')['default']
    Left4: typeof import('./src/components/view/Left4.vue')['default']
    Map: typeof import('./src/components/view/Map.vue')['default']
    Panel: typeof import('./src/components/content/Panel.vue')['default']
    Right1: typeof import('./src/components/view/Right1.vue')['default']
    Right2: typeof import('./src/components/view/Right2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubList: typeof import('./src/components/device/SubList.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
